# Generated by Django 2.1.5 on 2019-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190130_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='reg_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
