# Generated by Django 2.1.5 on 2019-01-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_score_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='roll_no',
        ),
    ]
