# Generated by Django 2.1.5 on 2019-01-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190130_2208'),
        ('academics', '0003_remove_attendance_roll_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session', 'quarter')},
        ),
    ]
